// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.Game = (function(superClass) {
  extend(Game, superClass);

  function Game() {
    return Game.__super__.constructor.apply(this, arguments);
  }

  Game.prototype.initialize = function() {
    var deck;
    this.set('deck', deck = new Deck());
    return this.listen();
  };

  Game.prototype.listen = function() {
    this.set('playerHand', this.get('deck').dealPlayer());
    this.set('dealerHand', this.get('deck').dealDealer());
    this.get('playerHand').on('busted', this.lose, this);
    this.get('playerHand').on('stand', function() {
      return this.get('dealerHand').dealerPlay();
    }, this);
    this.get('dealerHand').on('busted', this.win);
    return this.get('dealerHand').on('stand', this.compare, this);
  };

  Game.prototype.lose = function() {
    console.log('you lose!');
    return this.listen;
  };

  Game.prototype.win = function() {
    console.log('you win!');
    return this.listen;
  };

  Game.prototype.compare = function() {
    var dealerScore, playerScore;
    playerScore = this.get('playerHand').bestScore();
    dealerScore = this.get('dealerHand').bestScore();
    if (playerScore > dealerScore) {
      this.win();
    }
    if (playerScore === dealerScore) {
      console.log('push');
    }
    if (playerScore < dealerScore) {
      this.lose();
    }
    return this.listen;
  };

  return Game;

})(Backbone.Model);
